name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - run: docker build . -t hemaratna/mern-ecommerce-api
    - run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{}} --password-stdin
    - run: docker push hemaratna/mern-ecommerce-api:latest